- proposals/reference-types/Overview.md
Initial brain dump. Contains most of the ideas, but little of the explanation. :)
> Add first sketch of overview

- proposals/reference-types/Overview.md
I believe
`n < anyref` for all reftypes `t`
should be
`t < anyref` for all reftypes `t`
> Fix typo in subtype relation

- document/core/appendix/algorithm.rst
- document/core/appendix/index-instructions.rst
- document/core/appendix/index-rules.rst
- document/core/appendix/index-types.rst
- document/core/binary/instructions.rst
- document/core/binary/types.rst
- document/core/exec/instructions.rst
- document/core/exec/modules.rst
- document/core/exec/runtime.rst
- document/core/syntax/instructions.rst
- document/core/syntax/modules.rst
- document/core/syntax/types.rst
- document/core/text/instructions.rst
- document/core/text/modules.rst
- document/core/text/types.rst
- document/core/util/macros.def
- document/core/valid/instructions.rst
- document/core/valid/modules.rst
- document/core/valid/types.rst
First go at specifying the baseline proposal, analogous to #2:
* add types `anyref` and `eqref` (and internal `nullref`) and respective subtyping (splitting valtype into numtype and reftype)
* add instructions `ref.null`, `ref.isnull`, `ref.eq`, `get_table`, `set_table`
* allow multiple tables
* validation, execution, binary format and text format
* adjust appendix
This change should already be complete, but opcodes are preliminary; names of table instruction might also be subject to change, depending on pending main spec PR.
Edit: [Rendered version](https://webassembly.github.io/reference-types/core/index.html)
> [spec] First go at specification

- document/js-api/index.bs
- proposals/reference-types/Overview.md
First attempt at speccing JS reference value conversions
> [spec] JS API changes

- proposals/reference-types/Overview.md
The Exceptions link in Overview points to the outdated/obsolete version of the proposal, while the GC proposal link was broken. Updated both to the current versions.
> Fix links to broken/obsolete proposals

- interpreter/script/js.ml
- test/core/ref_is_null.wast
> [interpreter] Fix JS generator

- document/core/appendix/embedding.rst
- document/core/appendix/index-rules.rst
- document/core/appendix/properties.rst
- document/core/exec/modules.rst
- document/core/exec/runtime.rst
- document/core/util/macros.def
With the introduction of subtyping, the semantics can no longer infer the type of a global or table instance at runtime from its value or elements. Instead, table and global instances must be equipped with that type information explicitly (for uniformity, do the same for memories). This comes up both during import matching and in auxiliary judgements accompanying the soundness theorem.
(This change aligns with what we already have in the reference interpreter.)
Some minor oversights fixed as well.
> [spec] Correctly account for subtyping in global/table instances

- test/core/linking.wast
The module name in linking.wast wasm `Mref-ex`. This is not a valid variable name in JavaScript. I replaced the `-` with a `_`.
> Fix module name in test

- document/core/binary/modules.rst
This PR fixes issue https://github.com/WebAssembly/reference-types/issues/36.
In https://github.com/WebAssembly/reference-types/issues/18 we decided that the binary encoding of element segments in this proposal should be the same as for the bulk memory proposal. This PR does this change in the specification document.
As far as I can tell, the spec interpreter already has the correct behavior.
> Adjust binary format of element segments in the spec

- test/core/linking.wast
Apparently I missed some JS-incompatible names in https://github.com/WebAssembly/reference-types/pull/45.
> [test] Use more JS-compatible names

- document/js-api/index.bs
- test/js-api/limits.any.js
With multi-table we need a common implementation limit for the max number of tables.  Firefox uses 100K as the limit currently so that's what I'm proposing here, but it's just a strawman value - please discuss.
> Increase the table count limit to 100,000

- document/core/binary/modules.rst
- interpreter/binary/decode.ml
- interpreter/binary/encode.ml
- test/core/binary.wast
Due to recent changes in the bulk-memory proposal (https://github.com/WebAssembly/bulk-memory-operations/pull/109), the element segment encoding here does not match the one in the bulk-memory proposal anymore. Concretely, element segments with flag 0x02 have an additional 0x00 byte after the offset which is a place holder for a potential element kind field.
This PR does minimal changes to get the reference-types proposal and the bulk-memory proposal in sync again.
> Adjust element segment encoding to match the bulk-memory proposal

- test/core/ref_func.wast
Add a test with an invalid function index in a ref.func init expression.
> [test] Add negative test for ref.func globals

- document/core/valid/instructions.rst
I believe the intent is to check there is a result type that matches the default label type here.
> Fix typo in validation of br_table

- test/core/binary.wast
The recent rebase broke some tests because error messages changed.
> [tests] Fix test expectation

- document/core/appendix/properties.rst
- document/core/exec/conventions.rst
- document/core/exec/instructions.rst
- document/core/exec/modules.rst
- document/core/exec/runtime.rst
- document/core/text/instructions.rst
- document/core/text/modules.rst
- document/core/util/macros.def
- interpreter/README.md
- interpreter/exec/eval.ml
- interpreter/runtime/table.ml
- interpreter/runtime/table.mli
- interpreter/syntax/ast.ml
- interpreter/text/arrange.ml
- interpreter/text/lexer.mll
- interpreter/text/parser.mly
- proposals/reference-types/Overview.md
- test/core/elem.wast
After rebasing on the bulk proposal, this PR fixes all open todos in interpreter and spec:
- Move to small-step semantics for table instructions [interpreter].
- Add back-compat sugar for table instructions omitting table index [spec/interpreter].
- Add optional `item` keyword to syntactically represent multi-instr element expressions, analogous to syntax for offset. [spec/interpreter]
- Generalise bulk table ops to multiple tables [spec].
- A few smaller todos in spec (segment instantiation, removing funcelems).
Two things still missing after this (modulo new design questions):
- Adding declaration segments (#31) -- I already have a branch for that.
- Actual tests for bulk table ops involving multiple tables, which is in the intersection of the two proposals -- the respective tests are …
> Fix various TODOs

- document/core/appendix/index-rules.rst
- document/core/binary/instructions.rst
- document/core/valid/conventions.rst
- document/core/valid/instructions.rst
- document/core/valid/modules.rst
- interpreter/valid/valid.ml
- test/core/table-sub.wast
Binary format and validation weren't updated to multi-table yet.
Also fixed typing in interpreter, which didn't check that source elem type matches dest elem type. Added test.
Fixes oversights [noted](https://github.com/WebAssembly/reference-types/issues/74#issuecomment-585451924) by @fitzgen.
> [spec/interpreter/test] Fix binary & validation for table.copy/init

- test/harness/async_index.js
- test/harness/sync_index.js
script/js.ml changed and started emitting different JS harness code.
This commit updates sync_index.js and async_index.js to match.
> Update JS test harnesses to match changes to interpreter harness

- test/harness/async_index.js
- test/harness/sync_index.js
This applies the changes made to 'script/js.ml' to the
standalone test harnesses.
> Update test/harness/*_index.js for removing subtyping

- document/core/valid/conventions.rst
- document/core/valid/modules.rst
- interpreter/valid/valid.ml
- test/core/ref_func.wast
Resolves #76, as discussed in CG meeting.
> [spec/interpreter/test] Relax ref check to whole module

- test/core/unreached-invalid.wast
The original commit to add a bottom type removed this test as it
would now unexpectedly validate. Now that a bottom type is removed
it would be good to keep it.
> Re-add test that fails with a bottom type

- interpreter/script/js.ml
In the generated test files the generic imports contained a function that does not exist anymore. This caused all tests to fail. This PR removes the function from the imports.
> [tests] Delete leftover harness function

- document/core/appendix/index-instructions.rst
@rossberg, could you please take a look? Thanks
> Fix links to `table.fill`'s validation and execution in appendix

- test/core/global.wast
While `linking.wast` tests that we can link modules that are importing and
exporting mutable `externref` globals, there were no tests exercising
`global.{get,set}` on mutable `externref` globals.
@binji, please take a look, thanks!
> Add a test for mutating `externref` globals

- document/core/exec/instructions.rst
Fixes https://github.com/WebAssembly/reference-types/issues/105
@rossberg please take a look. Thanks!
> table.fill: Bounds check before mutating the table

- proposals/reference-types/Overview.md
> Remove type annotation on ref.is_null in overview

- document/core/syntax/instructions.rst
The incorrect description is a leftover from the original proposal,
which specified a ref.eq instruction:
https://github.com/WebAssembly/reference-types/commit/1f29a8ee7af86c45769fd130c67e09ad0f9b197f#diff-90422c6925e039f03d4bcf0359947b08R187-R190
> Fix decription of ref.func

- test/core/bulk.wast
- test/core/data.wast
- test/core/elem.wast
- test/core/linking.wast
- test/core/memory_copy.wast
- test/core/memory_fill.wast
- test/core/memory_init.wast
- test/core/table_copy.wast
- test/core/table_fill.wast
- test/core/table_get.wast
- test/core/table_init.wast
- test/core/table_set.wast
This PR fixes some failure strings in the spec tests:
1. Fixed `out of bound` to `out of bounds memory access` or `out of bounds table access`.
2. Fixed `uninitialized` to `uninitialized element`.
3. Fixed `undefined` to `undefined element`.
4. Fixed `indirect call` to `indirect call type mismatch`.
> [test] Uniform failure strings

- document/core/text/instructions.rst
- document/core/text/types.rst
- document/core/util/macros.def
Change to use the name from the follow-on typed function references proposal.  Fixes #123.
> Rename "refedtype" to "heaptype"

- document/core/exec/modules.rst
Fixes #112. The formal semantics was fine, but the prose wasn't. This introduces a recursion in the prose as well.
> [spec] Fix instantiation to handle ref.func in initializers

- document/core/binary/instructions.rst
- document/core/text/instructions.rst
> Fix table instructions indentation in spec

- document/js-api/index.bs
* table.[[Values]] was removed upstream but accidentally kept in a merge.
* table.get() was not updated to support non-funcref tables.
* DefaultValue() omitted funcref.
* Various typos were fixed.
> Fix some js-api bugs.

- document/js-api/index.bs
The core spec does not allow primitive types here; a 'table type' must contain a reftype.
> [js-api] Explicitly disallow creating Tables with non-reftypes.
